databases:
  - name: jwlmsdb
    plan: free
    databaseName: jw_lms
    user: jw_lms

services:
  - type: web
    plan: free
    name: john-willeit-institute
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn jw_lms.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jwlmsdb
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: "4"
