# Generated by Django 4.2.29 on 2026-04-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_material_course_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated each time the student saves their submission.'),
        ),
    ]
